package ma.fullstackclone.airbnb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PropertyCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPropertyCategoryAllPropertiesEquals(PropertyCategory expected, PropertyCategory actual) {
        assertPropertyCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertPropertyCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPropertyCategoryAllUpdatablePropertiesEquals(PropertyCategory expected, PropertyCategory actual) {
        assertPropertyCategoryUpdatableFieldsEquals(expected, actual);
        assertPropertyCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPropertyCategoryAutoGeneratedPropertiesEquals(PropertyCategory expected, PropertyCategory actual) {
        assertThat(expected)
            .as("Verify PropertyCategory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPropertyCategoryUpdatableFieldsEquals(PropertyCategory expected, PropertyCategory actual) {
        assertThat(expected)
            .as("Verify PropertyCategory relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPropertyCategoryUpdatableRelationshipsEquals(PropertyCategory expected, PropertyCategory actual) {
        assertThat(expected)
            .as("Verify PropertyCategory relationships")
            .satisfies(e -> assertThat(e.getProperties()).as("check properties").isEqualTo(actual.getProperties()));
    }
}
